ALTER TABLE "DB2INST1"."TDOCVER" 
	ADD CONSTRAINT "PK_TDOCVER" PRIMARY KEY;
	
	CREATE INDEX "DB2INST1"."XDOCVER" ON "DB2INST1"."TDOCVER" 
		("VER_TBNAME" ASC,
		"VER_NR" asc ,
		 "VER_DATE" ASC);
		


ALTER TABLE "DB2INST1"."TDOCVER" 
	ADD CONSTRAINT "PK_TDOCVER" PRIMARY KEY
		("VER_TBNAME",
		"VER_NR" ,
		 "VER_DATE");
		 
		 ALTER TABLE "DB2INST1"."TDOCVER" 
	drop CONSTRAINT "PK_TDOCVER" ;
	
		 ALTER TABLE "DB2INST1"."TDOCVER" 
	alter column "VER_NR"  set not null ;