--<ScriptOptions statementTerminator=";"/>

CREATE LARGE TABLESPACE "SNEWTAB"
	IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
	PAGESIZE 8 K
	MANAGED BY AUTOMATIC STORAGE
	AUTORESIZE YES
	MAXSIZE 100 M
	EXTENTSIZE 32
	BUFFERPOOL "IBMDEFAULTBP"
	OVERHEAD INHERIT
	TRANSFERRATE INHERIT
	DATA TAG INHERIT
	USING STOGROUP "IBMSTOGROUP";

--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "DB2INST1"."TNEWTAB" (
		"TREQUESTSTRING" VARCHAR(32000 OCTETS), 
		"TBNAME" VARCHAR(30 OCTETS) NOT NULL, 
		"TOWNER" VARCHAR(32 OCTETS), 
		"TDBA" VARCHAR(32 OCTETS), 
		"TDATABASE" VARCHAR(32 OCTETS), 
		"TBSPACE" VARCHAR(32 OCTETS), 
		"TDOMAIN" VARCHAR(20 OCTETS), 
		"THOUSEKEEPING" CHAR(1 OCTETS), 
		"TREL_TYPE" VARCHAR(30 OCTETS), 
		"TREL_RULES" VARCHAR(30 OCTETS), 
		"THOUSE_RULES" CHAR(20 OCTETS), 
		"TTYPE" VARCHAR(20 OCTETS), 
		"TREC_ESTIM" INTEGER, 
		"TREC_GROWTH" INTEGER, 
		"TCID" CHAR(1 OCTETS), 
		"TCID_RULES" CHAR(20 OCTETS), 
		"TUSE_UCC" CHAR(1 OCTETS), 
		"TUSE_DWH" CHAR(1 OCTETS), 
		"TUSE_ODS" CHAR(1 OCTETS), 
		"TUSE_CWF" CHAR(1 OCTETS), 
		"TUSE_IWF" CHAR(1 OCTETS), 
		"TUSE_OWF" CHAR(1 OCTETS), 
		"TUSE_DEP_MANAGER" CHAR(1 OCTETS), 
		"TDESCRIPTION" VARCHAR(50 OCTETS), 
		"TENTITY_DESCRIPTION" VARCHAR(6000 OCTETS), 
		"VER_NR" VARCHAR(10 OCTETS) NOT NULL, 
		"VER_DESCRIPTION" VARCHAR(50 OCTETS), 
		"VER_CHANGE_DATE" DATE, 
		"VER_CHANGE_NR" VARCHAR(10 OCTETS), 
		"VER_RESPONSIBLE" VARCHAR(30 OCTETS), 
		"REQ_TIMESTAMP" TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SNEWTAB"
	COMPRESS NO;

ALTER TABLE "DB2INST1"."TNEWTAB" ADD CONSTRAINT "TNEWTAB_PK" PRIMARY KEY
	("TBNAME", 
	 "REQ_TIMESTAMP");

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TCID" IS
'Contain Costumer Infiormation Data';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TCID_RULES" IS
'Rules to annonimize this Costumer Infiormation Data';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TDESCRIPTION" IS
'Table Description';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TDOMAIN" IS
'Which Domain use this table';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TENTITY_DESCRIPTION" IS
'Full description of use and handling in application';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TOWNER" IS
'Name of responsible dataowner';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TREC_ESTIM" IS
'How many Records willbe stores in table';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TREC_GROWTH" IS
'How much records will be insert wevery month';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TREL_RULES" IS
'Reload rules to use';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TREL_TYPE" IS
'Reload Type';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TTYPE" IS
'Type can be : Parameter, Master Data, Daily Data, Transactual Data  , open';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TUSE_CWF" IS
'Used in Cor work flow';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TUSE_DEP_MANAGER" IS
'Used from Department Manager';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TUSE_DWH" IS
'Used in DWH';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TUSE_IWF" IS
'Used in Inkasso work flow';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TUSE_ODS" IS
'Used in ODS';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TUSE_OWF" IS
'Used in OC work flow';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."TUSE_UCC" IS
'Used in UCC';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."VER_CHANGE_DATE" IS
'Date of change';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."VER_CHANGE_NR" IS
'Changenumber o deployment';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."VER_DESCRIPTION" IS
'Description of change';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."VER_NR" IS
'Versions Nubmer';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."VER_RESPONSIBLE" IS
'Person who did this change';

COMMENT ON TABLE "DB2INST1"."TNEWTAB" IS
'This Table contain all information of changes on the table which we need to generate the Business Documentation for the users';


COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."COL_KEY" IS
'Key like primary or foreing, NONE';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."COL_MANDATORY" IS
'Not clear what is needed';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."COL_NAME" IS
'Name of colum';



COMMENT ON TABLE "DB2INST1"."TNEWTAB" IS
'This Table contain all information of changes on the table which we need to generate the Business Documentation for the users';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."VER_CHANGE_DATE" IS 'Date of change';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."VER_CHANGE_NR" IS 'Changenumber o deployment';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."VER_DESCRIPTION" IS 'Description of change';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."VER_NR" IS 'Versions Nubmer';

COMMENT ON COLUMN "DB2INST1"."TNEWTAB"."VER_RESPONSIBLE" IS 'Person who did this change';


COMMENT ON TABLE "DB2INST1"."TNEWTAB" IS 'This Table contain all information of changes on the table which we need to generate the Business Documentation for the users';

