--<ScriptOptions statementTerminator=";"/>

CREATE LARGE TABLESPACE "SNEWCOL"
	IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
	PAGESIZE 8 K
	MANAGED BY AUTOMATIC STORAGE
	AUTORESIZE YES
	MAXSIZE 100 M
	EXTENTSIZE 32
	BUFFERPOOL "IBMDEFAULTBP"
	OVERHEAD INHERIT
	TRANSFERRATE INHERIT
	DATA TAG INHERIT
	USING STOGROUP "IBMSTOGROUP";
--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "DB2INST1"."TNEWCOL" (
		"COL_TBNAME" VARCHAR(50 OCTETS) NOT NULL, 
		"COL_NAME" VARCHAR(50 OCTETS) NOT NULL, 
		"COL_KEY" VARCHAR(2 OCTETS), 
		"COL_DESCRIPTION" VARCHAR(500 OCTETS), 
		"COL_FORMAT" VARCHAR(20 OCTETS), 
		"COL_DEFAULT" VARCHAR(20 OCTETS), 
		"COL_MANDATORY" VARCHAR(1 OCTETS), 
		"COL_CID" VARCHAR(1 OCTETS), 
		"COL_INFO" VARCHAR(3000 OCTETS), 
		"COL_TIMESTAMP" TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SDOCVER"
	COMPRESS NO;

ALTER TABLE "DB2INST1"."TNEWCOL" ADD CONSTRAINT "TNEWCOL_PK" PRIMARY KEY
	("COL_NAME", 
	 "COL_TBNAME", 
	 "COL_TIMESTAMP");

COMMENT ON COLUMN "DB2INST1"."TNEWCOL"."COL_CID" IS
'Contain Costumer information';

COMMENT ON COLUMN "DB2INST1"."TNEWCOL"."COL_DESCRIPTION" IS
'Description of ccontent';

COMMENT ON COLUMN "DB2INST1"."TNEWCOL"."COL_FORMAT" IS
'Used from Sysibm syscolumns';

COMMENT ON COLUMN "DB2INST1"."TNEWCOL"."COL_INFO" IS
'Business information';

COMMENT ON COLUMN "DB2INST1"."TNEWCOL"."COL_KEY" IS
'Key like primary or foreing, NONE';

COMMENT ON COLUMN "DB2INST1"."TNEWCOL"."COL_MANDATORY" IS
'Not clear what is needed';

COMMENT ON COLUMN "DB2INST1"."TNEWCOL"."COL_NAME" IS
'Name of colum';

COMMENT ON TABLE "DB2INST1"."TNEWCOL" IS
'This Table contain all data which we need to generate the requestet Table';


