--<ScriptOptions statementTerminator=";"/>

CREATE LARGE TABLESPACE "SDOCCOL"
	IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
	PAGESIZE 8 K
	MANAGED BY AUTOMATIC STORAGE
	AUTORESIZE YES
	MAXSIZE 100 M
	EXTENTSIZE 32
	BUFFERPOOL "IBMDEFAULTBP"
	OVERHEAD INHERIT
	TRANSFERRATE INHERIT
	DATA TAG INHERIT
	USING STOGROUP "IBMSTOGROUP";

