--<ScriptOptions statementTerminator=";"/>

DROP INDEX "DB2INST1"."XDOCTAB";

DROP TABLE "DB2INST1"."TDOCTAB";

CREATE TABLE "DB2INST1"."TDOCTAB" (
		"TBNAME" VARCHAR(30 OCTETS) NOT NULL, 
		"TDESCRIPTION" VARCHAR(50 OCTETS), 
		"TTYPE" VARCHAR(20 OCTETS), 
		"TREC_ESTIM" INTEGER, 
		"TREC_GROWTH" INTEGER, 
		"TDOMAIN" VARCHAR(20 OCTETS), 
		"TREL_TYPE" VARCHAR(30 OCTETS), 
		"TREL_RULES" VARCHAR(30 OCTETS), 
		"THOUSEKEEPING" CHAR(1 OCTETS), 
		"THOUSE_RULES" CHAR(20 OCTETS), 
		"TCID" CHAR(1 OCTETS), 
		"TCID_RULES" CHAR(20 OCTETS), 
		"TUSE_UCC" CHAR(1 OCTETS), 
		"TUSE_DWH" CHAR(1 OCTETS), 
		"TUSE_ODS" CHAR(1 OCTETS), 
		"TUSE_CWF" CHAR(1 OCTETS), 
		"TUSE_IWF" CHAR(1 OCTETS), 
		"TUSE_OWF" CHAR(1 OCTETS), 
		"TUSE_DEP_MANAGER" CHAR(1 OCTETS), 
		"TENTITY_DESCRIPTION" VARCHAR(6000 OCTETS), 
		"TOWNER" VARCHAR(32 OCTETS), 
		"TTIMESTAMP" CHAR(10 OCTETS) DEFAULT ' '
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SDOCTAB"
	COMPRESS NO;

CREATE INDEX "DB2INST1"."XDOCTAB"
	ON "DB2INST1"."TDOCTAB"
	("TBNAME"		ASC)
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COMPRESS NO;

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TBNAME" IS
'TABLE NAME';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TCID" IS
'Contain Costumer Infiormation Data';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TCID_RULES" IS
'Rules to annonimize this Costumer Infiormation Data';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TDESCRIPTION" IS
'Table Description';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TDOMAIN" IS
'Which Domain use this table';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TENTITY_DESCRIPTION" IS
'Full description of use and handling in application';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TOWNER" IS
'Name of responsible dataowner';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TREC_ESTIM" IS
'How many Records willbe stores in table';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TREC_GROWTH" IS
'How much records will be insert wevery month';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TREL_RULES" IS
'Reload rules to use';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TREL_TYPE" IS
'Reload Type';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TTYPE" IS
'Type can be : Parameter, Master Data, Daily Data, Transactual Data  , open';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TUSE_CWF" IS
'Used in Cor work flow';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TUSE_DEP_MANAGER" IS
'Used from Department Manager';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TUSE_DWH" IS
'Used in DWH';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TUSE_IWF" IS
'Used in Inkasso work flow';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TUSE_ODS" IS
'Used in ODS';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TUSE_OWF" IS
'Used in OC work flow';

COMMENT ON COLUMN "DB2INST1"."TDOCTAB"."TUSE_UCC" IS
'Used in UCC';

COMMENT ON TABLE "DB2INST1"."TDOCTAB" IS
'This Table contain all data which we need to generate the Business Documentation for the users';

