--<ScriptOptions statementTerminator=";"/>

DROP TABLE "DB2INST1"."TDOCCOL";

CREATE TABLE "DB2INST1"."TDOCCOL" (
		"COL_TBNAME" VARCHAR(30 OCTETS) NOT NULL, 
		"COL_NAME" VARCHAR(50 OCTETS) NOT NULL, 
		"COL_KEY" VARCHAR(2 OCTETS), 
		"COL_DESCRIPTION" VARCHAR(500 OCTETS), 
		"COL_FORMAT" VARCHAR(20 OCTETS), 
		"COL_DEFAULT" VARCHAR(20 OCTETS), 
		"COL_MANDATORY" VARCHAR(1 OCTETS), 
		"COL_CID" VARCHAR(1 OCTETS), 
		"COL_INFO" VARCHAR(3000 OCTETS), 
		"COL_TIMESTAMP" CHAR(10 OCTETS)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "SDOCCOL"
	COMPRESS NO;

COMMENT ON COLUMN "DB2INST1"."TDOCCOL"."COL_CID" IS
'Contain Costumer information';

COMMENT ON COLUMN "DB2INST1"."TDOCCOL"."COL_DESCRIPTION" IS
'Description of ccontent';

COMMENT ON COLUMN "DB2INST1"."TDOCCOL"."COL_FORMAT" IS
'Used from Sysibm syscolumns';

COMMENT ON COLUMN "DB2INST1"."TDOCCOL"."COL_INFO" IS
'Business information';

COMMENT ON COLUMN "DB2INST1"."TDOCCOL"."COL_KEY" IS
'Key like primary or foreing, NONE';

COMMENT ON COLUMN "DB2INST1"."TDOCCOL"."COL_MANDATORY" IS
'Not clear what is needed';

COMMENT ON COLUMN "DB2INST1"."TDOCCOL"."COL_NAME" IS
'Name of colum';

COMMENT ON COLUMN "DB2INST1"."TDOCCOL"."COL_TBNAME" IS
'TABLE NAME';

COMMENT ON TABLE "DB2INST1"."TDOCCOL" IS
'This Table contain all information of changes on the table which we need to generate the Business Documentation for the users';


