SELECT TB.NAME, TB.CREATOR, TB.TBSPACE, TB.REMARKS, TB.CTIME, TB.STATS_TIME, TB.STATISTICS_PROFILE, TB.LASTUSED, 
			TB.ALTER_TIME, TB.COLCOUNT, 
			TDESCRIPTION,  TTYPE,  TREC_ESTIM,  TREC_GROWTH,  TDOMAIN,  TREL_TYPE,  TREL_RULES,  THOUSEKEEPING, 
 			THOUSE_RULES,  TCID,  TCID_RULES,  TUSE_UCC,  TUSE_DWH,  TUSE_ODS,  TUSE_CWF,  TUSE_IWF, 
 			TUSE_OWF,  TUSE_DEP_MANAGER,  TENTITY_DESCRIPRION , TOWNER 
  FROM SYSIBM.SYSTABLES AS TB LEFT OUTER JOIN SYSIBM.SYSTABLESPACES AS TS 
  		ON TB.TBSPACE = TS.TBSPACE, 
     ( SELECT *
      FROM DB2INST1.TDOCTAB 
      WHERE TBNAME = 'SEMINAR' 
      )  
  WHERE TB.NAME = 'SEMINAR'  
  and TTIMESTAMP = (SELECT  MAX(TTIMESTAMP)
      FROM TDOCTAB 
      WHERE TBNAME = 'SEMINAR' 
      )  
;

SELECT  MAX(TTIMESTAMP)
      FROM TDOCTAB 
      WHERE TBNAME = 'SEMINAR' 


      ;